BE: fix: allow consecutive external logins (regression from 59900722)
error: when updating user during login with auth type 'external' it rejects with error if the user was found but not updated because an  update was not necessary